apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-query-deployment
  namespace: axion-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: telemetry-query-deployment

  template:
    metadata:
      labels:
        app: telemetry-query-deployment

    spec:
      containers:
        - name: telemetry-query
          image: ghcr.io/contactanamika55/axion-telemetry-query-service:30abaa0
          imagePullPolicy: Always

          ports:
            - containerPort: 8000
              protocol: TCP